---
- hosts: all:!local
  user: vagrant
  sudo: True
  gather_facts: False

  tasks:
  # sysctl kernel settings
  - name: 'limit the ability of processes to have simultaneous write and execute access to memory'
    sysctl: name=kernel.exec-shield value=1 state=present reload=yes ignoreerrors=yes

  - name: 'implement virtual address space randomization'
    sysctl: name=kernel.randomize_va_space state=present reload=yes ignoreerrors=yes

  # sysctl network settings
  - name: 'do not accept IPv4 source-routed packets on any interface'
    sysctl: name=net.ipv4.conf.all.accept_source_route value=0 state=present reload=yes ignoreerrors=yes

  - name: 'do not accept ICMPv4 redirect packets on any interface'
    sysctl: name=net.ipv4.conf.all.accept_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'IP forwarding for IPv4 must not be enabled, unless the system is a router.'
    sysctl: name=net.ipv4.ip_forward value=0 state=present reload=yes ignoreerrors=yes

  - name: 'do not accept ICMPv4 secure redirect packets on any interface'
    sysctl: name=net.ipv4.conf.all.secure_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'use a reverse-path filter for IPv4 network traffic'
    sysctl: name=net.ipv4.conf.all.rp_filter value=1 state=present reload=yes ignoreerrors=yes

  - name: 'do must not accept ICMPv4 secure redirect packets by default'
    sysctl: name=net.ipv4.conf.default.secure_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'ignore ICMPv6 redirects by default'
    sysctl: name=net.ipv6.conf.default.accept_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'do not send ICMPv4 redirects by default'
    sysctl: name=net.ipv4.conf.default.send_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'do not send ICMPv4 redirects from any interface'
    sysctl: name=net.ipv4.conf.all.send_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'log Martian packets'
    sysctl: name=net.ipv4.conf.all.log_martians value=1 state=present reload=yes  ignoreerrors=yes

  - name: 'ignore IPv4 ICMP redirect messages.'
    sysctl: name=net.ipv4.conf.default.accept_redirects value=0 state=present reload=yes ignoreerrors=yes

  - name: 'do not respond to ICMPv4 sent to a broadcast address.'
    sysctl: name=net.ipv4.icmp_echo_ignore_broadcasts value=1 state=present reload=yes ignoreerrors=yes

  - name: 'ignore ICMPv4 bogus error responses.'
    sysctl: name=net.ipv4.icmp_ignore_bogus_error_responses value=1 state=present reload=yes ignoreerrors=yes

  - name: 'disable TCP timestamp responses'
    sysctl: name=net.ipv4.tcp_timestamps value=0 state=present reload=yes ignoreerrors=yes

