---

- name: 'get Oracle Java 8 with wget'
  become: yes
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-x64.rpm
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /home/vagrant/jdk-8u91-linux-x64.rpm
  register: download
  tags:
    - oracle_java8

- name: 'install Oracle Java 8'
  become: yes
  yum:
    name: jdk-8u91-linux-x64.rpm
    state: present
    update_cache: yes
  register: yuminstall
  tags:
    - oracle_java8

- name: 'Ensure presence of Java profile'
  become: yes
  file:
    path: /etc/profile.d/jre.sh
    state: touch
    mode: 0755
  tags:
    - oracle_java8

- name: 'fix JAVA_HOME'
  become: yes
  lineinfile:
    line: 'export JAVA_HOME=/usr/java/jdk1.8.0_91'
    dest: /etc/profile.d/jre.sh
    state: present
  tags:
    - oracle_java8
