#!/usr/bin/env ansible-playbook

- name: 'audit.yml'
  hosts: webservers
  gather_facts: True
  become: yes

  vars:
  - benchmark: 'U_RedHat_6_V1R8_STIG_SCAP_1-1_Benchmark.zip'
  - stig_baseurl: 'http://iasecontent.disa.mil/stigs/zip/July2015'

  roles:
    - RHEL6-STIG

  tasks:

  - name: 'add packages for security audit'
    yum: name=openscap-utils state=present
    tags:
      - audit
      
  - name: 'download from http://iase.disa.mil/'
    get_url: url={{stig_baseurl}}/{{benchmark}} dest=/tmp/{{benchmark}}
    tags:
      - audit

  - name: 'unzip Security Content Automation Protocol Content'
    command: unzip -o /tmp/{{benchmark}}
    tags:
      - audit

  - name: 'make this benchmark work for Centos instead of RHEL'
    shell: "perl -pi -e 's/redhat:enterprise_linux/centos:centos/;' *.xml"
    tags:
      - audit

  - name: 'run the SCAP tool and create rhel-stig-report.html'
    command: "oscap xccdf eval \
      --profile MAC-1_Sensitive \
      --results /tmp/results.xml \
      --report /tmp/rhel-stig-report.html \
      --cpe U_RedHat_6_V1R8_STIG_SCAP_1-1_Benchmark-cpe-dictionary.xml \
      U_RedHat_6_V1R8_STIG_SCAP_1-1_Benchmark-xccdf.xml"
    no_log: yes
    ignore_errors: yes
    tags:
      - audit
      
  - name: 'fetch report into /tmp/rhel-stig-report.html'
    fetch: dest=/tmp/rhel-stig-report.html src=/root/rhel-stig-report.html flat=yes
    become: no
    tags:
      - audit

      
