#!/usr/bin/env ansible-playbook
# playbook for dbserver tier

- name: 'dbservers.yml'
  hosts: dbservers
  become: yes
  gather_facts: True

  vars_files:
    - include: dbservers/secrets.yml

  pre_tasks:
    - include: dbservers/pre_tasks.yml

  roles:
    - common
    - ntp
    - pam
    - ssh
    - postgres
    - rsyslog

  tasks: []

  post_tasks:
  - name: 'verify tcp listening socket for PostgreSQL'
    wait_for: port=5432 timeout=5
    tags:
      - test

  - name: 'create database'
    postgresql_db: name=database template='template0' encoding='UTF-8'
    tags:
      - config

  - name: 'create dba user'
    postgresql_user: db=database name='dba' password='{{dba_password}}'
    tags:
      - config
      - secret
