#!/usr/bin/env ansible-playbook
# playbook for dbserver tier

- name: 'dbservers.yml'
  hosts: dbservers
  become: yes
  gather_facts: True

  vars_files:
    - dbservers/secrets.yml

  pre_tasks:
    - include: dbservers/pre_tasks.yml

  roles:
    - { role: common, tags: 'common' }
    - { role: ntp, tags: 'ntp' }
    - { role: pam, tags: 'pam' }
    - { role: rsyslog, tags: 'rsyslog' }
    - { role: ssh, tags: 'ssh' }
    - { role: bbaassssiiee.el_postgres_role, tags: 'postgres' }

  tasks: []

  post_tasks:
    - include: dbservers/post_tasks.yml

  handlers: []