# playbook for dbserver tier

- name: database server setup
  hosts: dbservers
  gather_facts: True

  pre_tasks:
    - include: dbservers/pre_tasks.yml

  roles:
    - bbaassssiiee.commoncentos
    - postgres

  tasks: []

  post_tasks:
    - include: dbservers/post_tasks.yml
