#!/usr/bin/env ansible-playbook
# playbook for dbserver tier

- name: 'dbservers.yml'
  hosts: dbservers
  become: yes
  gather_facts: True

  vars_files:
    - dbservers/secrets.yml

  pre_tasks:
    - include: dbservers/pre_tasks.yml

  roles:
    - { role: common, tags: 'common' }
    - ntp
    - pam
    - ssh
    - bbaassssiiee.el_postgres_role
    - rsyslog

  tasks: []

  post_tasks:
    - include: dbservers/post_tasks.yml

