#!/usr/bin/env ansible-playbook
# playbook for dbserver tier

- name: database server setup
  hosts: dbservers
  become: yes
  gather_facts: True

  pre_tasks:
    - include: dbservers/pre_tasks.yml

  roles:
    - common
    - ntp
    - pam
    - ssh
    - postgres
    - rsyslog

  tasks: []

  post_tasks:
    - include: dbservers/post_tasks.yml
