## This lists roles that the playbooks depend on

# Cross platform Java role, needs vars to be configured.

- src: bbaassssiiee.commoncentos
  path: ./roles/

- src: hostclick.tomcat
  path: ./roles/
