## This lists roles that the playbooks depend on

# Cross platform Java role, needs vars to be configured.

- src: geerlingguy.java
  path: ./roles/

- src: hostclick.tomcat
  path: ./roles/

- src: https://github.com/MindPointGroup/RHEL6-STIG.git
  version: devel
  path: ./roles/
