#!/usr/bin/env ansible-playbook
- name: 'vulnerability_scan.yml'
  hosts: webservers
  gather_facts: False
  become: yes

  vars:
    - requirements:
        - tabulate
        - untangle
        - pytest
        - python-coveralls
        - pytest-cov

  tasks:
  - name: 'add packages for security audit'
    yum:
      name: {{ item }}
      state: present
    with_items:
     - unzip
     - git
     - openscap-utils
     - python-argparse
     - python-pip
    tags:
      - scan

  - name: 'add python modules for security audit'
    pip:
      name: {{item}}
    with_items: "{{ requirements }}"
    tags:
      - scan

  - name: 'download Red Hat Security Response Team OVAL definitions, part 1'
    get_url:
      url: http://www.redhat.com/security/data/metrics/com.redhat.rhsa-all.xccdf.xml
      dest: /root/com.redhat.rhsa-all.xccdf.xml
    tags:
      - scan

  - name: 'download Red Hat Security Response Team OVAL definitions, part 2'
    get_url:
      url: http://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml
      dest: /root/com.redhat.rhsa-all.xml
    tags:
      - scan

  - name: 'run the SCAP tool and create vulnerability-report.html'
    command: "oscap xccdf eval --results /root/vulnerability-results.xml \
      --report /root/vulnerability-report.html \
      /root/com.redhat.rhsa-all.xccdf.xml"
    tags:
      - scan

  - name: 'fetch report into /tmp/vulnerability-report.html'
    fetch:
      dest: /tmp/vulnerability-report.html
      src: /root/vulnerability-report.html
      flat: yes
    tags:
      - scan
      - demo

  - name: 'copy report to webserver'
    copy:
      src: /tmp/vulnerability-report.html
      dest: /var/www/html/vulnerability-report.html
      mode: 0644
    tags:
      - scan
      - demo
