#!/usr/bin/env ansible-playbook
# playbook for webserver tier

- name: 'webservers.yml'
  hosts: webservers
  become: yes

  vars_files:
    - webservers/secrets.yml

  pre_tasks:
    - include: webservers/pre_tasks.yml

  roles:
    - { role: common, tags: 'common' }
    - { role: ntp, tags: 'ntp' }
    - { role: pam, tags: 'pam' }
    - { role: rsyslog, tags: 'rsyslog' }
    - { role: ssh, tags: 'ssh' }
    - { role: tcpwrappers, tags: 'tcpwrappers' }
    - { role: reverse_proxy, tags: 'reverse_proxy' }
    - { role: oracle_java8, tags: 'oracle_java8' }
    - { role: hostclick.tomcat, tags: 'hostclick.tomcat' }

  tasks: []

  post_tasks:
    - include: webservers/post_tasks.yml

  handlers:
    - name: restart iptables
      service:
        name: iptables
        state: restarted
