#!/usr/bin/env ansible-playbook
# playbook for webserver tier

- name: webapp server setup
  hosts: webservers
  become: yes

  roles:
    - common
    - pam
    - rsyslog
    - ssh
    - tcpwrappers
    - reverse_proxy
    - oracle_java8
    - hostclick.tomcat


  post_tasks:
    - include: webservers/post_tasks.yml

  handlers:
    - name: restart iptables
      service: name=iptables state=restarted
