#!/usr/bin/env ansible-playbook
# playbook for webserver tier

- name: 'webservers.yml'
  hosts: webservers
  become: yes

  pre_tasks:
    - include: webservers/pre_tasks.yml

  roles:
    - common
    - ntp
    - pam
    - rsyslog
    - ssh
    - tcpwrappers
    - reverse_proxy
    - oracle_java8
    - hostclick.tomcat

  post_tasks:
    - include: webservers/post_tasks.yml

  handlers:
    - name: restart iptables
      service: name=iptables state=restarted
