# playbook for webserver tier

- name: webapp server setup
  hosts: webservers
  sudo: yes

  pre_tasks:
    - include: webservers/pre_tasks.yml

  roles:
    - common
    - geerlingguy.java
    - hostclick.tomcat

  post_tasks:
    - include: webservers/post_tasks.yml
