# playbook for webserver tier

- name: webapp server setup
  hosts: webservers
  become: yes

  pre_tasks:
    - include: webservers/pre_tasks.yml

  roles:
    - restrict

    - common
    - ssh
    - reverse_proxy
    - geerlingguy.java
    - hostclick.tomcat
#    - RHEL6-STIG

  post_tasks:
    - include: webservers/post_tasks.yml

  handlers:
    - name: restart iptables
      service: name=iptables state=restarted
