---

- name: restart sshd
  debug:
    msg: "checking config first"
  changed_when: True
  notify:
    - check sshd configuration
    - restart sshd - after config check

- name: check sshd configuration
  command: "/usr/sbin/sshd -t"
  register: result
  changed_when: "result.rc != 0"
  always_run: yes

- name: restart sshd - after config check
  service:
    name: sshd
    state: restarted