---
# these are common tasks for linux installs

- name: 'be sure ntp is installed'
  become: yes
  yum: pkg=ntp state=installed
  tags: ntp

- name: 'be sure ntp is configured'
  become: yes
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: 'be sure ntpd is running and enabled'
  become: yes
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: 'set hostname'
  become: yes
  hostname: name='{{inventory_hostname}}'

- name: 'persist hostname in hosts file'
  become: yes
  lineinfile: dest=/etc/hosts regexp='{{inventory_hostname}}'
              line='{{ansible_eth1.ipv4.address}}   {{inventory_hostname}}'
              state=present

- name: 'persist localhost in hosts file'
  become: yes
  lineinfile: dest=/etc/hosts regexp='^127.0.0.1'
              line='127.0.0.1   localhost.localdomain localhost'
              state=present

- name: 'add domain name resolver'
  become: yes
  lineinfile: dest=/etc/resolv.conf regexp='^nameserver'
              line='nameserver {{dns_nameserver}}' state=present

- name: 'remove /etc/localtime'
  become: yes
  action: file path=/etc/localtime state=absent

- name: 'link /etc/localtime to /usr/share/zoneinfo/CET'
  become: yes
  action: file src=/usr/share/zoneinfo/CET dest=/etc/localtime state=link owner=root group=root

- name: 'copy /etc/motd file'
  become: yes
  template: src=templates/motd.j2 dest=/etc/motd
            owner=root group=root mode=0640 backup=no
