---

- name: 'install packages for systems management'
  yum: name={{ item }} state=present
  with_items:
   - iptables
   - libselinux-python
   - libsemanage-python
   - ntp
   - openswan
   - policycoreutils-python
   - screen
   - unzip
  tags:
    - common
    
- name: 'system security patches and updates must be installed and up-to-date'
  yum: name=* state=latest
  tags:
    - common

- name: 'ensure auditing at boot time'
  command: sed -i '/^\tkernel/ s/$/ audit=1/' /etc/grub.conf
  tags:
    - common

# EPEL Yum repository adds Extra Packages for Enterprise Linux
- name: 'add EPEL yum repo'
  yum: name=epel-release state=present
  when: internet is defined

- name: 'set hostname'
  hostname: name={{ inventory_hostname }}
  tags:
    - common

- name: 'build hosts file'
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  tags:
    - common
     
- name: 'create banner for login'
  copy: 
      src: issue 
      dest: /etc/{{ item }} 
      owner: root 
      group: root 
      mode: "0644" 
      backup: yes
  with_items:
    - issue
    - issue.net
  tags:
    - common
