---

- name: 'lock password user for ansible user'
  become: yes
  command: usermod -L {{ansible_user}}

- name: 'install python virtualenv and pip'
  become: yes
  yum: name={{ item }} state=installed
  with_items:
    - python-virtualenv
    - python-pip

- name: 'copy python library requirements for pip'
  copy: src=requirements.txt dest=/tmp/requirements.txt

- name: 'create virtualenv for ansible'
  pip: requirements=/tmp/requirements.txt virtualenv=/home/{{ansible_user}} virtualenv_site_packages=yes

- name: 'set temporary attributes for files'
  become: yes
  ignore_errors: yes
  command: chattr -i /home/{{ansible_user}}/{{item}}
  with_items:
    - .bashrc
    - .profile
    - .bash_profile
    - .exrc

- name: 'set permissions on virtualenv'
  become: yes
  command: chmod -R go+rx /home/{{ansible_user}}

- name: 'install the Korn shell'
  become: yes
  yum: name=ksh state=installed

- name: 'link ksh to rksh'
  become: yes
  file: src=/bin/ksh dest=/bin/rksh owner=root group=root state=hard

- name: 'link bash to rbash'
  become: yes
  file: src=/bin/bash dest=/bin/rbash owner=root group=root state=hard force=yes

- name: 'copy tools'
  become: yes
  command: cp {{ item }} /home/{{ansible_user}}/bin
  with_items:
    - /bin/mkdir
    - /bin/echo
    - /bin/rm
    - /bin/rbash
    - /bin/tar

- name: 'link tar to gtar'
  become: yes
  file: src=/home/{{ansible_user}}/bin/tar dest=/home/{{ansible_user}}/bin/gtar owner=root group=root state=hard force=yes

- name: 'copy sh'
  become: yes
  command: cp /bin/sh /home/{{ansible_user}}/bin/sh creates=/home/{{ansible_user}}/bin/sh

- name: 'set permissions'
  become: yes
  shell: chmod go+rx /home/{{ ansible_user }}/bin/{{ item }}
  with_items:
    - mkdir
    - echo
    - rm
    - sh
    - rbash
    - tar

- name: 'copy sudo'
  become: yes
  command: cp /usr/bin/sudo /home/{{ansible_user}}/bin/sudo creates=/home/{{ansible_user}}/bin/sudo

- name: 'set suid on sudo'
  become: yes
  file: path=/home/{{ ansible_user }}/bin/sudo mode=4111 owner=root group=root

- name: 'copy chattr'
  become: yes
  command: cp /usr/bin/chattr /home/{{ansible_user}}/bin/chattr creates=/home/{{ansible_user}}/bin/chattr

- name: 'set permissions on chattr'
  become: yes
  file: path=/home/{{ ansible_user }}/bin/chattr mode=0700 owner=root group=root

- name: 'create bashrc'
  template: src=bashrc.j2 dest=/home/{{ansible_user}}/.bashrc mode=0400

- name: 'lock bashrc file for writing'
  become: yes
  shell: chattr +i /home/{{ansible_user}}/.bashrc

- name: 'create exrc'
  copy: src=exrc dest=/home/{{ansible_user}}/.exrc mode=0400

- name: 'lock exrc file for writing'
  become: yes
  shell: chattr +i /home/{{ansible_user}}/.exrc

- name: 'make sure rbash is for non-interactive use'
  copy: src=bash_profile
            dest=/home/{{ ansible_user }}/.bash_profile
            owner={{ ansible_user }}
            group={{ ansible_user }}
            mode=0400

- name: 'lock .bash_profile file for writing'
  become: yes
  shell: chattr +i /home/{{ansible_user}}/.bash_profile

- name: 'make sure ksh is for non-interactive use'
  copy: src=profile
            dest=/home/{{ ansible_user }}/.profile
            owner={{ ansible_user }}
            group={{ ansible_user }}
            mode=0400

- name: 'lock .profile file for writing'
  become: yes
  shell: chattr +i /home/{{ansible_user}}/.profile

- name: 'restricted shell for ansible user'
  become: yes
  user: name={{ ansible_user }} shell=/bin/rbash
